name: Publish

on:
  create:
    tags:
      - 'v*'

jobs:
  publish-gpr:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@rodogir'
      - run: yarn install
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
